server:
  port: 8081

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
open-api:
  service:
    url: http://spring-gateway:8000
spring:
  application:
    name: drawaing-auth-service

  # MySQL
  datasource:
    url: jdbc:mysql://j12a101.p.ssafy.io:3306/drawaing
    username: root
    password: dhrlack990298
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  # Redis
  data:
    redis:
      host: j12a101.p.ssafy.io
      port: 6379
      password: ckwjdans9*
      timeout: 6000

  kafka:
    bootstrap-servers: localhost:10000,localhost:10001,localhost:10002
  #    consumer:
  #      group-id: member-service
  #      auto-offset-reset: earliest
  #      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  #      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
  #      properties:
  #        spring.json.trusted.packages: com.aioi.drawaing.*
  #    producer:
  #      key-serializer: org.apache.kafka.common.serialization.StringSerializer
  #      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  #    template:
  #      default-topic: deduct-points

  # Mail
  mail:
    host: smtp.gmail.com
    port: 587
    username: ckwjdans4182@gmail.com
    password: uxonnnydkidbnqkn
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
  # Security OAuth
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 854121372939-8i1cfqakibmpnd7rkv6es8mrdmng9eqs.apps.googleusercontent.com
            clientSecret: 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
            redirect-uri: '${oauth2.redirect-uri}/api/v1/{action}/oauth2/code/{registrationId}'
            scope: profile, email
          naver:
            clientId: VnJRiFxpOMCmT8LiFHNQ
            clientSecret: K8ejEfwUnW
            redirect-uri: '${oauth2.redirect-uri}/api/v1/{action}/oauth2/code/{registrationId}'
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
              - profile_image
            client-name: Naver
          kakao:
            clientId: 35f76fac7038d1387a29167f210fd236
            clientSecret: c3sObhFT30F9sXjdUs8njysOCrUgrpMU
            redirect-uri: '${oauth2.redirect-uri}/api/v1/{action}/oauth2/code/{registrationId}'
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - account_email
              - profile_image
            client-name: Kakao
            client-authentication-method: client_secret_post
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
cloud:
  aws:
    credentials:
      access-key: AKIAVUIF4KAHXNKU73PP
      secret-key: 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
    s3:
      bucket-name: drawaing-bucket
    region:
      static: ap-northeast-2

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web.cors: DEBUG
    org.hibernate: INFO

jwt:
  secret: UDVaY0VRREoyaEl2d2JlWXFFN2haOWF3ekRxbFBzTnpscEFFaE5mdDBSZw==
  access-token-expiration-time: 86400000  # 1일 (밀리초 단위)
  refresh-token-expiration-time: 604800000  # 7일 (밀리초 단위)
  refresh-token-expiration-time-cookie: 604800 # 7일 (초 단위)

oauth2:
  redirect-uri: http://localhost:8081 #https://www.drawaing.site

app:
  oauth2:
    authorizedRedirectUris: http://localhost:5173/oauth/redirect

ImageUrl:
  defaultCharacter: https://drawaing-bucket.s3.ap-northeast-2.amazonaws.com/images/character/default.jpg