spring:
  data:
    mongodb:
      uri: mongodb://gkrdh99:dhrlack990298@j12a101.p.ssafy.io:27017/drawing_game?authSource=admin

jwt:
  secret: UDVaY0VRREoyaEl2d2JlWXFFN2haOWF3ekRxbFBzTnpscEFFaE5mdDBSZw==


logging:
  level:
    org:
      springframework:
        web:
          socket: DEBUG
        messaging:
          simp:
            stomp: DEBUG