server:
  port: 8082

spring:
  application:
    name: drawing-game-service

  profiles:
    active: test

  config:
    import: "classpath:/application-secret.yml"

  kafka:
    bootstrap-servers: localhost:10000, localhost:10001, localhost:10002

#  data:
#    redis:
#      host: localhost
#      port: 6379
#      timeout: 6000

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

open-api:
  service:
    url: /


#logging:
#  level:
#    org.springframework.web.socket: DEBUG
#    org.springframework.messaging.simp.stomp: DEBUG